### ISSUE TITLE
At any time the Observe Node doesn't send any command

### ISSUE THREAD

**Issue by nicedevil007** [lopelex/node-red-contrib-harmony#14] opened 2020-09-28 20:23 UTC
Heya, I have a small problem. After updating node-red for example it is restarted completly and then it seems that the observe node doesn't recognize any button pressed on the harmony...

so is it possible to set the ip with an inject node after start of node-red? maybe this can help to fix it.

**Comment by lopelex** [comment] 2020-10-03 10:49
Duplicate of #15

**Closed by lopelex** 2020-10-03 10:49 UTC
